api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    title: 'API NFT'
    description: 'Collection de NFT'
    version: '0.0.1'